kube-prometheus-stack:
  namespaceOverride: prometheus
  grafana:
    # TODO provide this via cli
    adminPassword: foobar
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: public
        cert-manager.io/cluster-issuer: letsencrypt-prometheus
      hosts:
        - prometheus-craigmiller160.ddns.net