{{- range $ingress := .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingress.name }}
  annotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
spec:
  rules:
  {{- range $host := $ingress.hosts }}
    - host: {{- if not .Values.environment }} {{ $host.name }} {{- else }} {{ .Values.environment }}-{{ $host.name }} {{- end}}
      http:
        paths:
          {{- range $service := $host.services}}
          - path: {{ $service.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ tpl (.serviceName) $ }}
                port:
                  number: {{ $service.portNumber }}
          {{- end}}
  {{- end }}
  tls:
    - secretName: {{ $ingress.certSecretName }}
      hosts:
      {{- range $host := $ingress.hosts }}
        - {{ tpl (.name) $ }}
      {{- end}}
---
{{- end}}