{{- range $ingress := .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingress.name }}
  annotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: letsencrypt-{{ $.Values.clusterissuer.suffix }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # TODO this is bad because it'll redirect on anything that ends in "s". Temporary fix, not permanent
      rewrite ^(\/.*[^\/s])$ $1/ redirect;
    {{- if $ingress.backendIsHttps }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- end}}
spec:
  rules:
  {{- range $host := $ingress.hosts }}
    - host: {{- if not $.Values.environment }} {{ $host.name }} {{- else }} {{ $.Values.environment }}-{{ $host.name }} {{- end}}
      http:
        paths:
          {{- range $service := $host.services}}
          - path: {{ $service.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $service.serviceName }}
                port:
                  number: {{ $service.portNumber }}
          {{- end}}
  {{- end }}
  tls:
    - secretName: {{ $ingress.certSecretName }}
      hosts:
      {{- range $host := $ingress.hosts }}
        - {{- if not $.Values.environment }} {{ $host.name }} {{- else }} {{ $.Values.environment }}-{{ $host.name }} {{- end}}
      {{- end}}
---
{{- end}}