appName: nfs-server
ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
volumes:
  - name: downloads-directory
    hostPath: /home/craig/Downloads
    mountPath: /exports
csi-driver-nfs:
  kubeletDir: /var/snap/microk8s/common/var/lib/kubelet
