apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: nfs-server
          image: erichough/nfs-server:2.2.1
          envFrom:
            - configMapRef:
                name: nfs-server-config
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
            {{- range $volume := .Values.volumes }}
            - name: {{ $volume.name }}
              mountPath: {{ $volume.mountPath }}
            {{- end}}
      volumes:
        {{- range $volume := .Values.volumes }}
        - name: {{ $volume.name }}
          hostPath:
            path: {{ $volume.hostPath }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP