apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: nfs-server.infra-prod
  share: /exports
# TODO what should this policy be?
{{/*reclaimPolicy: Delete*/}}
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1