ingress_test:
  name: ingress-test
ingress:
  - name: apps-ingress
    certSecretName: apps-cert-secret
    hosts:
      - name: "{{ .Values.environment }}-apps-craigmiller160.ddns.net"
        services:
          - path: /ingress-test
            serviceName: "{{ .Values.ingress_test.name }}"
            portNumber: 80
          - path: /funcoast-hi
            serviceName: funcoast-hi-client
            portNumber: 443
          - path: /auth-management
            serviceName: auth-management-ui
            portNumber: 443
          - path: /video-manager
            serviceName: video-manager-client
            portNumber: 443
          - path: /market-tracker
            serviceName: market-tracker-ui
            portNumber: 443
  - name: infra-ingress
    certSecretName: infra-cert-secret
    hosts:
      - name: "{{ .Values.environment }}-infra-craigmiller160.ddns.net"
        services:
          - path: /onepassword
            serviceName: 1password-connect
            portNumber: 8081
      - name: "{{ .Values.environment }}-nexus-craigmiller160.ddns.net"
        services:
          - path: /
            serviceName: nexus
            portNumber: 8081
      - name: "{{ .Values.environment }}-nexus-docker-craigmiller160.ddns.net"
        services:
          - path: /
            serviceName: nexus
            portNumber: 8083