clusterissuer:
  suffix: infra
ingress:
  - name: infra-ingress
    certSecretName: infra-cert-secret
    hosts:
      - name: infra-craigmiller160.ddns.net
        services:
          - path: /onepassword/(.*)
            serviceName: onepassword-connect
            portNumber: 8080
      - name: nexus-craigmiller160.ddns.net
        services:
          - path: /(.*)
            serviceName: nexus
            portNumber: 8081
      - name: nexus-docker-craigmiller160.ddns.net
        services:
          - path: /(.*)
            serviceName: nexus
            portNumber: 8083