clusterissuer:
  suffix: apps
ingress:
  - name: apps-https-backend-ingress
    certSecretName: apps-https-backend-cert-secret
    backendIsHttps: true
    hosts:
      - name: apps-craigmiller160.ddns.net
        services:
          - path: /(funcoast-hi(/.*)?)
            serviceName: funcoast-hi-client
            portNumber: 443
          - path: /(auth-management(/.*)?)
            serviceName: auth-management-ui
            portNumber: 443
          - path: /(market-tracker(/.*)?)
            serviceName: market-tracker-ui
            portNumber: 443
          - path: /oauth2/(.*)?
            serviceName: sso-oauth2-server
            portNumber: 8443