ingress:
  - name: infra-ingress
    certSecretName: infra-cert-secret
    hosts:
      - name: infra-craigmiller160.ddns.net
        services:
          - path: /onepassword/(.*)
            serviceName: onepassword-connect
            portNumber: 8080
          # TODO two problems here: 1. in another namespace, and 2. requires HTTPS
#          - path: /dashboard/(.*)
#            serviceName: kubernetes-dashboard
#            portNumber: 443
      - name: nexus-craigmiller160.ddns.net
        services:
          - path: /(.*)
            serviceName: nexus
            portNumber: 8081
      - name: nexus-docker-craigmiller160.ddns.net
        services:
          - path: /(.*)
            serviceName: nexus
            portNumber: 8083