clusterissuer:
  suffix: apps
ingress:
  - name: apps-https-backend-ingress
    certSecretName: apps-https-backend-cert-secret
    backendIsHttps: true
    hosts:
      - name: apps-craigmiller160.ddns.net
        services:
          - path: /oauth2/(.*)?
            serviceName: sso-oauth2-server
            portNumber: 8443