clusterissuer:
  suffix: apps
ingress:
  - name: apps-https-backend-ingress
    certSecretName: apps-https-backend-cert-secret
    backendIsHttps: true
    hosts:
      - name: apps-craigmiller160.ddns.net
        services:
          - path: /(funcoast-hi(/.*)?)
            serviceName: funcoast-hi-client
            portNumber: 443
          - path: /(auth-management(/.*)?)
            serviceName: auth-management-ui
            portNumber: 443
          - path: /(video-manager(/.*)?)
            serviceName: video-manager-client
            portNumber: 443
          - path: /(market-tracker(/.*)?)
            serviceName: market-tracker-ui
            portNumber: 443
  - name: apps-http-backend-ingress
    certSecretName: app-http-backend-cert-secret
    hosts:
      - name: apps-craigmiller160.ddns.net
        services:
          - path: /(torrent(/.*)?)
            serviceName: qbittorrent
            portNumber: 80