app-deployment:
  appName: db-backup-service
  image: nexus-docker-craigmiller160.ddns.net/db-backup-service:latest
  # Optional, defaults to 1
  replicas: 1
  configMaps:
    - db-backup-service-configmap
  secrets:
    - envVariable: db.postgres.user
      secretName: postgres-root-account
      secretKey: username
  livenessProbe:
    # Option #1
    exec:
      command:
        - sh
        - /output/liveness.sh
    # Option #2
    httpGet:
      path: /actuator/health
      port: 8443
      scheme: HTTPS
  volumes:
    # Will create PVC
    - name: volume1
      type: PVC
      deploymentMountPath: /output
    # Will use HostPath
    - name: volume2
      type: HostPath
      hostPath: /otherPath
      deploymentMountPath: /output
  # Will create service if specified
  ports:
    - containerPort: 8443
      # Only required if multiple ports
      name: ThePort
      # If no nodePort, will be ClusterIP, otherwise will be NodePort
      nodePort: 30010
      # Optional, defaults to TCP
      protocol: TCP