appName: name
deployment:
  image: image-name
  ports:
    - 8443
  configMaps:
    - configmap-name
  secrets:
    - envVariable: variable-name
      secretName: secret-name
      secretKey: key-in-secret
  livenessProbe:
    path: /the/path
    port: 1234
    scheme: scheme
service:
  type: ClusterIP
  ports:
    - containerPort: 8443