app-deployment:
  appName: db-backup-service
  deployment:
    image: nexus-docker-craigmiller160.ddns.net/db-backup-service:latest
    configMaps:
      - db-backup-service-configmap
    ports:
      - 8443
    secrets:
      - envVariable: db.postgres.user
        secretName: postgres-root-account
        secretKey: username
    livenessProbe:
      # Option #1
      exec:
        command:
          - sh
          - /output/liveness.sh
      # Option #2
      httpGet:
        path: /actuator/health
        port: 8443
        scheme: HTTPS
  volumes:
    - name: db-backup-service-volume
      type: PVC
      deploymentMountPath: /output
  service:
    enable: true
    type: ClusterIP
    ports:
      - containerPort: 8443