apiVersion: cert-manager.io/v1alpha2
kind: CluserIssuer
metadata:
  name: letsencrypt
spec:
  acme:
  server: https://acme-v02.api.letsencrypt.org/directory
  email: regoo707@gmail.com
  privateKeySecretRef:
    name: letsencrypt
  solvers:
    - http01:
  ingress:
    class: public